### ISSUE TITLE
Some missing dash-if profiles in the schematron

### ISSUE THREAD

**Issue by niteeshbhat** [Dash-Industry-Forum/DASH-IF-Conformance#45] opened 2018-11-05 15:10 UTC
<a href="https://github.com/niteeshbhat"><img src="https://avatars3.githubusercontent.com/u/13762418?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [niteeshbhat](https://github.com/niteeshbhat)**
_Friday Oct 19, 2018 at 14:51 GMT_
_Originally opened as https://github.com/Dash-Industry-Forum/Conformance-Software/issues/420_

----

ex : dash-if-simple.
This profile is not identified in the existing schematron.

**Comment by eceozturk** [comment] 2018-11-29 15:20
Duplicate of #138

**Closed by eceozturk** 2018-11-29 15:20 UTC
Labels: DASH-IF, duplicate
