### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by DaniDana** [Dash-Industry-Forum/DASH-IF-Conformance#537] opened 2021-05-12 16:47 UTC
I have no idea how to fix this.
![aham](https://user-images.githubusercontent.com/67022727/118013473-123ef600-b34a-11eb-9c00-e2f4b8509211.png)

**Comment by rbouqueau** [comment] 2021-05-12 16:54
Thanks for reporting. Could you please provide us with the information to reproduce the issue?

**Comment by DaniDana** [comment] 2021-05-13 14:04
I am new to this, you mean provide the code?

**Comment by rbouqueau** [comment] 2021-05-20 14:09
Could you please give us some context about what you are executing?

Take into account that we probably need to reproduce your issue to be able to fix it.

**Comment by linehammer** [comment] 2021-11-01 04:46
Since the string stores an array of characters, just like arrays the position of each character is represented by an index (starting from 0). If you try to access the character of a String at the  index is either negative or greater than the size of the string, a StringIndexOutOfBoundsException is thrown. For some methods such as the [java substring](http://net-informations.com/java/string/substring.htm), charAt method, this exception also is thrown when the index is equal to the size of the string.

Just like other exceptions you can handle this exception by wrapping the code that is prone to it within try catch. In the catch block catch the exception of type IndexOutOfBoundsException or, StringIndexOutOfBoundsException.

**Comment by dsilhavy** [comment] 2022-02-02 11:57
@DaniDana Where did you see this problem. Which class and which module. How can we reproduce?

**Comment by rbouqueau** [comment] 2024-04-03 19:32
No way to reproduce. Closing.

**Closed by rbouqueau** 2024-04-03 19:32 UTC
Labels: Bug, Low priority
