### ISSUE TITLE
allow Role@value = 'main' in multiple audio AdaptationSet

### ISSUE THREAD

**Issue by cnkangj** [Dash-Industry-Forum/DASH-IF-Conformance#539] opened 2021-07-28 16:34 UTC
When running an MPD file with multiple AdaptionSet with Role@value 'main', Conformance tool flags it as error below.
###'HbbTV check violated: Section E.2.2 - If there is more than one audio AdaptationSet, exactly one shall be labelled with Role@value 'main' ', but found 2 Role@value 'main' in Period 1

However, spec allows it. From DVB DASH spec*, "It is possible to have multiple Adaptation Sets with @value set to "main", however, they shall be distinguished by other aspects described in the MPD such as (but not limited to) @lang or @codecs or the AudioChannelConfiguration descriptor".

* Digital Video Broadcasting (DVB); MPEG-DASH Profile for Transport of ISO BMFF Based DVB Services over IP Based Networks, DVB Document A168, Oct 2019

An example is http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events-multimainlang.mpd

**Comment by dsilhavy** [comment] 2022-02-02 11:59
Duplicate of #523

**Closed by dsilhavy** 2022-02-02 11:59 UTC
