### ISSUE TITLE
MPD.Java not keeeping step with MPD.xsd amendments

### ISSUE THREAD

**Issue by OwlHute** [Dash-Industry-Forum/DASH-IF-Conformance#478] opened 2019-10-30 10:03 UTC
The MPD XML validation in file:

https://github.com/Dash-Industry-Forum/DASH/blob/master/mpdvalidator/src/org/iso/mpeg/dash/MPD.java

does not match the XML schema in :

https://github.com/Dash-Industry-Forum/DASH/blob/master/mpdvalidator/schemas/DASH-MPD.xsd

For example, DASH-MPD.xsd defines the following block types which can be immediately contained in the <MPD> block, but these are not allowed by MPD.java and thus they are rejected by the web-based MPD validator (at https://conformance.dashif.org/ for example)

• EssentialProperty
• SupplementalProperty
• UTCTiming

The reason for this is that each time a developer amends DASH-MPD.xsd, they should also auto-generate from it a consistent version of MPD.java by running the JAXB “xjc” Java utility and committing both files together back into the repository. See:

https://docs.oracle.com/javase/tutorial/jaxb/intro/index.html

https://docs.oracle.com/javase/tutorial/jaxb/intro/examples.html

But it looks like this has not been happening for several years (since 2013, the date year in MPD.java), and thus MPD.java has been falling further and further behind the more recent changes made to the XSD!

**Comment by eceozturk** [comment] 2019-10-30 12:26
Thank you reporting this. 

Although it is correct that the java files should be updated whenever there is an amendment to DASH-MPD.xsd, the problem of failing MPD Validation is because the order of the elements in the MPD should follow the order in DASH-MPD.xsd. So, actually the mentioned block types are accepted by the conformance software and the issue is with the order of the elements.

An example MPD with UTC timing element that passes the MPD validation (notice the UTCTiming element location): 
- https://livesim.dashif.org/livesim/utc_direct-head/testpic_2s/Manifest.mpd

For more information, the below closed issues are also related to this:
- #248 
- #225 

I am closing this issue now, noting that the update of the java files should be done from now on. Please reopen if the issue persists.

**Closed by eceozturk** 2019-10-30 12:26 UTC
