### ISSUE TITLE
Sidecar Subtitle files in Manifest fails 'Schematron Validation' due to length being longer than maxSegmentDuration

### ISSUE THREAD

**Issue by mrp1977** [Dash-Industry-Forum/DASH-IF-Conformance#524] opened 2020-09-07 13:29 UTC
[manifestwithsidecarsubs.txt](https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/files/5183299/manifestwithsidecarsubs.txt)
When using the mpd validation tool, https://conformance.dashif.org, with a manifest which contains sidecar subtitle files it fails 'schematron validation' due to 'The d attribute of a SegmentTimeline shall not exceed the value give by the MPD maxSegmentDuration attribute.'

We believe this should not show as a fail as the sidecar is not, and should not be,  segmented

I have attached such a manifest to the ticket.

This ticket is a replica of https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/505

The original ticket has not been picked up and was raised in May of this year. If further information is required then please do let me know.

Many Thanks
[manifestwithsidecarsubs.txt](https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/files/5183308/manifestwithsidecarsubs.txt)

**Comment by dsilhavy** [comment] 2022-02-02 11:42
Duplicate of #505

**Closed by dsilhavy** 2022-02-02 11:42 UTC
